package com.alpha.model;

public enum ApplicationStatus {
    DRAFT, SUBMITTED, UNDER_REVIEW, ELIGIBILITY_PASSED, ELIGIBILITY_FAILED, DOCUMENTS_VERIFIED, DOCUMENTS_REJECTED, SHORTLISTED, MATCHED, FUNDED, REJECTED, WITHDRAWN
}
